apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cost-onprem.fullname" . }}-rbac-api-access
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: networkpolicy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rbac-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: gateway
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: cost-management-api
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: cost-management-masu
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: ros-api
      ports:
        - protocol: TCP
          port: {{ include "cost-onprem.rbac.service.port" . }}
