apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cost-onprem.fullname" . }}-aws-config
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
data:
  config: |
    [default]
    region = {{ include "cost-onprem.storage.s3Region" . }}
    s3 =
      signature_version = s3v4
      addressing_style = {{ include "cost-onprem.storage.s3AddressingStyle" . }}
